spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNomingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

banner:
  location: classpath:/example/banner.txt

  
